apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: true
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  rules:
  - http:
      paths:
      - path: /pi
        backend:
          serviceName: podinfo
          servicePort: 9899
      - path: /hw
        backend:
          serviceName: sample-app
          servicePort: 8082
      - path: /ad
        backend:
          serviceName: additional-app
          servicePort: 8081
      - path: /hasura(/|$)(.*)
        backend:
          serviceName: hasura
          servicePort: 81
